-- ─── Index (posés après le chargement : plus rapide qu'à l'insertion) ───
CREATE UNIQUE INDEX accounts_number_key ON public.accounts USING btree (number);
CREATE UNIQUE INDEX "alertes_acquittees_userId_cle_key" ON public.alertes_acquittees USING btree ("userId", cle);
CREATE INDEX "alertes_acquittees_userId_idx" ON public.alertes_acquittees USING btree ("userId");
CREATE INDEX articles_ext_designation_idx ON public.articles_ext USING btree (designation);
CREATE INDEX articles_ext_famille_idx ON public.articles_ext USING btree (famille);
CREATE INDEX articles_ext_kind_idx ON public.articles_ext USING btree (kind);
CREATE UNIQUE INDEX bank_accounts_code_key ON public.bank_accounts USING btree (code);
CREATE INDEX "bilan_comptable_exerciceId_idx" ON public.bilan_comptable USING btree ("exerciceId");
CREATE INDEX "bon_appro_lignes_bonId_idx" ON public.bon_appro_lignes USING btree ("bonId");
CREATE UNIQUE INDEX "bon_appro_lignes_bonId_refArt_key" ON public.bon_appro_lignes USING btree ("bonId", "refArt");
CREATE INDEX bons_approvisionnement_etat_idx ON public.bons_approvisionnement USING btree (etat);
CREATE UNIQUE INDEX bons_approvisionnement_reference_key ON public.bons_approvisionnement USING btree (reference);
CREATE INDEX bons_approvisionnement_utilisateur_idx ON public.bons_approvisionnement USING btree (utilisateur);
CREATE INDEX "borderau_lignes_borderauId_idx" ON public.borderau_lignes USING btree ("borderauId");
CREATE INDEX charges_fixes_etat_idx ON public.charges_fixes USING btree (etat);
CREATE UNIQUE INDEX "cheques_chequierId_numero_key" ON public.cheques USING btree ("chequierId", numero);
CREATE INDEX cheques_echeance_idx ON public.cheques USING btree (echeance);
CREATE INDEX cheques_etat_idx ON public.cheques USING btree (etat);
CREATE INDEX chequiers_banque_idx ON public.chequiers USING btree (banque);
CREATE UNIQUE INDEX "clients_userId_key" ON public.clients USING btree ("userId");
CREATE UNIQUE INDEX "commercials_userId_key" ON public.commercials USING btree ("userId");
CREATE UNIQUE INDEX "commercials_vehicleId_key" ON public.commercials USING btree ("vehicleId");
CREATE UNIQUE INDEX "component_user_droit_login_fonctionId_key" ON public.component_user_droit USING btree (login, "fonctionId");
CREATE INDEX component_user_droit_login_idx ON public.component_user_droit USING btree (login);
CREATE UNIQUE INDEX depots_code_key ON public.depots USING btree (code);
CREATE INDEX "document_lines_ext_refArt_idx" ON public.document_lines_ext USING btree ("refArt");
CREATE INDEX "document_lines_ext_refDoc_idx" ON public.document_lines_ext USING btree ("refDoc");
CREATE UNIQUE INDEX documents_reference_key ON public.documents USING btree (reference);
CREATE INDEX "documents_ext_codeCli_idx" ON public.documents_ext USING btree ("codeCli");
CREATE INDEX "documents_ext_dateDoc_idx" ON public.documents_ext USING btree ("dateDoc");
CREATE INDEX "documents_ext_nature_typeDoc_idx" ON public.documents_ext USING btree (nature, "typeDoc");
CREATE INDEX documents_ext_tiers_idx ON public.documents_ext USING btree (tiers);
CREATE INDEX "documents_ext_transferFrom_idx" ON public.documents_ext USING btree ("transferFrom");
CREATE INDEX "documents_ext_transferTo_idx" ON public.documents_ext USING btree ("transferTo");
CREATE INDEX "ecritures_compta_dateEcriture_idx" ON public.ecritures_compta USING btree ("dateEcriture");
CREATE INDEX "ecritures_compta_exerciceId_numCompte_idx" ON public.ecritures_compta USING btree ("exerciceId", "numCompte");
CREATE INDEX "ecritures_compta_numPiece_idx" ON public.ecritures_compta USING btree ("numPiece");
CREATE INDEX "ecritures_compta_refDoc_idx" ON public.ecritures_compta USING btree ("refDoc");
CREATE INDEX enregistrements_visite_commercial_idx ON public.enregistrements_visite USING btree (commercial);
CREATE INDEX "enregistrements_visite_ligneId_idx" ON public.enregistrements_visite USING btree ("ligneId");
CREATE INDEX erp_missions_commercial_idx ON public.erp_missions USING btree (commercial);
CREATE INDEX "erp_missions_dateOrdre_idx" ON public.erp_missions USING btree ("dateOrdre");
CREATE INDEX erp_missions_etat_idx ON public.erp_missions USING btree (etat);
CREATE INDEX "erp_reglements_borderauId_idx" ON public.erp_reglements USING btree ("borderauId");
CREATE INDEX "erp_reglements_datePay_idx" ON public.erp_reglements USING btree ("datePay");
CREATE INDEX "erp_reglements_dayId_idx" ON public.erp_reglements USING btree ("dayId");
CREATE UNIQUE INDEX "erp_reglements_sens_idSource_key" ON public.erp_reglements USING btree (sens, "idSource");
CREATE INDEX erp_reglements_sens_idx ON public.erp_reglements USING btree (sens);
CREATE INDEX "evenements_opportunite_opportuniteId_idx" ON public.evenements_opportunite USING btree ("opportuniteId");
CREATE UNIQUE INDEX exercices_compta_annee_key ON public.exercices_compta USING btree (annee);
CREATE INDEX "frais_mission_dayId_idx" ON public.frais_mission USING btree ("dayId");
CREATE UNIQUE INDEX gpao_gammes_gamme_key ON public.gpao_gammes USING btree (gamme);
CREATE INDEX "gpao_gammes_refArt_idx" ON public.gpao_gammes USING btree ("refArt");
CREATE UNIQUE INDEX gpao_jalonnements_code_key ON public.gpao_jalonnements USING btree (code);
CREATE INDEX "gpao_nomenclature_lignes_refArt_idx" ON public.gpao_nomenclature_lignes USING btree ("refArt");
CREATE INDEX "gpao_nomenclature_lignes_refNom_idx" ON public.gpao_nomenclature_lignes USING btree ("refNom");
CREATE UNIQUE INDEX gpao_operations_code_key ON public.gpao_operations USING btree (code);
CREATE INDEX "gpao_operations_gamme_gammeId_idx" ON public.gpao_operations_gamme USING btree ("gammeId");
CREATE INDEX "gpao_operations_of_refDoc_idx" ON public.gpao_operations_of USING btree ("refDoc");
CREATE INDEX "gpao_plannification_dateDebut_idx" ON public.gpao_plannification USING btree ("dateDebut");
CREATE INDEX "gpao_plannification_refDoc_idx" ON public.gpao_plannification USING btree ("refDoc");
CREATE UNIQUE INDEX gpao_postes_charge_code_key ON public.gpao_postes_charge USING btree (code);
CREATE UNIQUE INDEX "grh_bulletin_codeEmploye_sessionId_key" ON public.grh_bulletin USING btree ("codeEmploye", "sessionId");
CREATE INDEX "grh_bulletin_sessionId_idx" ON public.grh_bulletin USING btree ("sessionId");
CREATE INDEX "grh_conge_codeEmploye_idx" ON public.grh_conge USING btree ("codeEmploye");
CREATE INDEX "grh_conge_sessionId_idx" ON public.grh_conge USING btree ("sessionId");
CREATE INDEX grh_contrats_etat_idx ON public.grh_contrats USING btree (etat);
CREATE INDEX "grh_contrats_personnelId_idx" ON public.grh_contrats USING btree ("personnelId");
CREATE UNIQUE INDEX grh_impo_du_key ON public.grh_impo USING btree (du);
CREATE INDEX grh_personnel_actif_idx ON public.grh_personnel USING btree (actif);
CREATE UNIQUE INDEX "grh_personnel_codeEmploye_key" ON public.grh_personnel USING btree ("codeEmploye");
CREATE INDEX grh_personnel_nom_idx ON public.grh_personnel USING btree (nom);
CREATE UNIQUE INDEX "grh_pointage_codeEmploye_sessionId_key" ON public.grh_pointage USING btree ("codeEmploye", "sessionId");
CREATE INDEX "grh_pointage_sessionId_idx" ON public.grh_pointage USING btree ("sessionId");
CREATE UNIQUE INDEX grh_typecnss_code_key ON public.grh_typecnss USING btree (code);
CREATE UNIQUE INDEX grille_salaire_regime_categorie_echelon_key ON public.grille_salaire USING btree (regime, categorie, echelon);
CREATE UNIQUE INDEX "inventaire_lignes_inventaireId_refArt_key" ON public.inventaire_lignes USING btree ("inventaireId", "refArt");
CREATE INDEX "inventaire_lignes_refArt_idx" ON public.inventaire_lignes USING btree ("refArt");
CREATE INDEX inventaires_etat_idx ON public.inventaires USING btree (etat);
CREATE UNIQUE INDEX inventaires_reference_key ON public.inventaires USING btree (reference);
CREATE UNIQUE INDEX journal_entries_reference_key ON public.journal_entries USING btree (reference);
CREATE UNIQUE INDEX journaux_compta_code_key ON public.journaux_compta USING btree (code);
CREATE INDEX "ligne_mission_codeCli_idx" ON public.ligne_mission USING btree ("codeCli");
CREATE INDEX "ligne_mission_dayId_idx" ON public.ligne_mission USING btree ("dayId");
CREATE INDEX ligne_mission_etat_idx ON public.ligne_mission USING btree (etat);
CREATE UNIQUE INDEX "list_droit_access_component_funcName_key" ON public.list_droit_access USING btree (component, "funcName");
CREATE INDEX list_droit_access_component_idx ON public.list_droit_access USING btree (component);
CREATE UNIQUE INDEX "managers_userId_key" ON public.managers USING btree ("userId");
CREATE INDEX "mouvements_compte_compteId_dateMvt_idx" ON public.mouvements_compte USING btree ("compteId", "dateMvt");
CREATE INDEX "mouvements_depot_refArt_idx" ON public.mouvements_depot USING btree ("refArt");
CREATE INDEX "mouvements_depot_refDoc_idx" ON public.mouvements_depot USING btree ("refDoc");
CREATE INDEX "numeros_serie_numSerie_idx" ON public.numeros_serie USING btree ("numSerie");
CREATE INDEX "numeros_serie_refArt_idx" ON public.numeros_serie USING btree ("refArt");
CREATE INDEX "numeros_serie_refDoc_idx" ON public.numeros_serie USING btree ("refDoc");
CREATE INDEX objectifs_annee_mois_idx ON public.objectifs USING btree (annee, mois);
CREATE UNIQUE INDEX objectifs_vendeur_mois_annee_key ON public.objectifs USING btree (vendeur, mois, annee);
CREATE INDEX "opportunites_codeCli_idx" ON public.opportunites USING btree ("codeCli");
CREATE INDEX opportunites_etape_idx ON public.opportunites USING btree (etape);
CREATE UNIQUE INDEX orders_reference_key ON public.orders USING btree (reference);
CREATE INDEX "panier_lignes_panierId_idx" ON public.panier_lignes USING btree ("panierId");
CREATE UNIQUE INDEX "panier_lignes_panierId_refArt_key" ON public.panier_lignes USING btree ("panierId", "refArt");
CREATE INDEX paniers_utilisateur_etat_idx ON public.paniers USING btree (utilisateur, etat);
CREATE UNIQUE INDEX param_compta_cle_key ON public.param_compta USING btree (cle);
CREATE INDEX parametrage_bilan_type_idx ON public.parametrage_bilan USING btree (type);
CREATE INDEX partners_charge_idx ON public.partners USING btree (charge);
CREATE UNIQUE INDEX "partners_matriculeF_unique" ON public.partners USING btree (upper(btrim("matriculeF"))) WHERE (("matriculeF" IS NOT NULL) AND (btrim("matriculeF") <> ''::text));
CREATE INDEX partners_nature_idx ON public.partners USING btree (nature);
CREATE INDEX "partners_raisonSocial_idx" ON public.partners USING btree ("raisonSocial");
CREATE UNIQUE INDEX partners_tel_unique_nouveaux ON public.partners USING btree (regexp_replace(regexp_replace(COALESCE(tel, ''::text), '\D'::text, ''::text, 'g'::text), '^(00216|216)'::text, ''::text)) WHERE (("creePar" IS NOT NULL) AND (tel IS NOT NULL) AND (regexp_replace(COALESCE(tel, ''::text), '\D'::text, ''::text, 'g'::text) <> ''::text));
CREATE INDEX plan_comptable_classe_idx ON public.plan_comptable USING btree (classe);
CREATE UNIQUE INDEX "plan_comptable_numCompte_key" ON public.plan_comptable USING btree ("numCompte");
CREATE UNIQUE INDEX "plan_comptable_standard_numCompte_key" ON public.plan_comptable_standard USING btree ("numCompte");
CREATE UNIQUE INDEX products_reference_key ON public.products USING btree (reference);
CREATE INDEX "projet_jalons_projetId_idx" ON public.projet_jalons USING btree ("projetId");
CREATE INDEX "projets_codeCli_idx" ON public.projets USING btree ("codeCli");
CREATE INDEX projets_etat_idx ON public.projets USING btree (etat);
CREATE UNIQUE INDEX purchase_documents_reference_key ON public.purchase_documents USING btree (reference);
CREATE INDEX "reclamation_client_codeCli_idx" ON public.reclamation_client USING btree ("codeCli");
CREATE INDEX "reclamation_client_dayId_idx" ON public.reclamation_client USING btree ("dayId");
CREATE INDEX reclamation_client_etat_idx ON public.reclamation_client USING btree (etat);
CREATE INDEX ref_tables_kind_idx ON public.ref_tables USING btree (kind);
CREATE UNIQUE INDEX reglements_reference_key ON public.reglements USING btree (reference);
CREATE INDEX "rubrique_employe_codeEmploye_idx" ON public.rubrique_employe USING btree ("codeEmploye");
CREATE UNIQUE INDEX "rubrique_employe_rubriqueId_codeEmploye_sessionId_key" ON public.rubrique_employe USING btree ("rubriqueId", "codeEmploye", "sessionId");
CREATE INDEX "rubrique_employe_sessionId_idx" ON public.rubrique_employe USING btree ("sessionId");
CREATE UNIQUE INDEX rubrique_paie_code_key ON public.rubrique_paie USING btree (code);
CREATE INDEX "sous_fam_art_codeFamille_idx" ON public.sous_fam_art USING btree ("codeFamille");
CREATE INDEX stock_depots_emplacement_idx ON public.stock_depots USING btree (emplacement);
CREATE UNIQUE INDEX "stock_depots_refArt_emplacement_key" ON public.stock_depots USING btree ("refArt", emplacement);
CREATE UNIQUE INDEX stock_movements_reference_key ON public.stock_movements USING btree (reference);
CREATE INDEX "stock_movements_ext_createdAt_idx" ON public.stock_movements_ext USING btree ("createdAt");
CREATE INDEX "stock_movements_ext_refArt_idx" ON public.stock_movements_ext USING btree ("refArt");
CREATE INDEX "stock_movements_ext_refDoc_idx" ON public.stock_movements_ext USING btree ("refDoc");
CREATE UNIQUE INDEX suppliers_code_key ON public.suppliers USING btree (code);
CREATE INDEX "tickets_sav_codeCli_idx" ON public.tickets_sav USING btree ("codeCli");
CREATE INDEX tickets_sav_etat_idx ON public.tickets_sav USING btree (etat);
CREATE UNIQUE INDEX tickets_sav_reference_key ON public.tickets_sav USING btree (reference);
CREATE INDEX "traite_bancaire_codeTiers_idx" ON public.traite_bancaire USING btree ("codeTiers");
CREATE INDEX traite_bancaire_echeance_idx ON public.traite_bancaire USING btree (echeance);
CREATE INDEX traite_bancaire_etat_idx ON public.traite_bancaire USING btree (etat);
CREATE UNIQUE INDEX traite_bancaire_reference_key ON public.traite_bancaire USING btree (reference);
CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);
CREATE UNIQUE INDEX users_login_key ON public.users USING btree (login);
CREATE UNIQUE INDEX vehicles_plate_key ON public.vehicles USING btree (plate);
CREATE INDEX "vehicules_operations_prochaineDate_idx" ON public.vehicules_operations USING btree ("prochaineDate");
CREATE INDEX "vehicules_operations_vehicleId_idx" ON public.vehicules_operations USING btree ("vehicleId");
