-- ─── Clés étrangères ───
ALTER TABLE public.account_entries ADD CONSTRAINT "account_entries_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.account_entries ADD CONSTRAINT "account_entries_journalEntryId_fkey" FOREIGN KEY ("journalEntryId") REFERENCES journal_entries(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.bilan_comptable ADD CONSTRAINT "bilan_comptable_exerciceId_fkey" FOREIGN KEY ("exerciceId") REFERENCES exercices_compta(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.bon_appro_lignes ADD CONSTRAINT "bon_appro_lignes_bonId_fkey" FOREIGN KEY ("bonId") REFERENCES bons_approvisionnement(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.cheques ADD CONSTRAINT "cheques_chequierId_fkey" FOREIGN KEY ("chequierId") REFERENCES chequiers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.claims ADD CONSTRAINT "claims_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES clients(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.clients ADD CONSTRAINT "clients_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES commercials(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.clients ADD CONSTRAINT "clients_userId_fkey" FOREIGN KEY ("userId") REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.commercials ADD CONSTRAINT "commercials_userId_fkey" FOREIGN KEY ("userId") REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.commercials ADD CONSTRAINT "commercials_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES vehicles(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.component_user_droit ADD CONSTRAINT "component_user_droit_fonctionId_fkey" FOREIGN KEY ("fonctionId") REFERENCES list_droit_access(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.document_lines ADD CONSTRAINT "document_lines_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES documents(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.document_lines ADD CONSTRAINT "document_lines_productId_fkey" FOREIGN KEY ("productId") REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.document_lines_ext ADD CONSTRAINT "document_lines_ext_refDoc_fkey" FOREIGN KEY ("refDoc") REFERENCES documents_ext("refDoc") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.documents ADD CONSTRAINT "documents_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES clients(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.documents ADD CONSTRAINT "documents_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES commercials(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.documents_ext ADD CONSTRAINT "documents_ext_dayId_fkey" FOREIGN KEY ("dayId") REFERENCES erp_missions(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.ecritures_compta ADD CONSTRAINT "ecritures_compta_codeJournal_fkey" FOREIGN KEY ("codeJournal") REFERENCES journaux_compta(code) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.ecritures_compta ADD CONSTRAINT "ecritures_compta_exerciceId_fkey" FOREIGN KEY ("exerciceId") REFERENCES exercices_compta(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.enregistrements_visite ADD CONSTRAINT "enregistrements_visite_ligneId_fkey" FOREIGN KEY ("ligneId") REFERENCES ligne_mission(id) ON DELETE CASCADE;
ALTER TABLE public.erp_reglements ADD CONSTRAINT "erp_reglements_borderauId_fkey" FOREIGN KEY ("borderauId") REFERENCES erp_borderaux(id) ON DELETE SET NULL;
ALTER TABLE public.erp_reglements ADD CONSTRAINT "erp_reglements_dayId_fkey" FOREIGN KEY ("dayId") REFERENCES erp_missions(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.evenements_opportunite ADD CONSTRAINT "evenements_opportunite_opportuniteId_fkey" FOREIGN KEY ("opportuniteId") REFERENCES opportunites(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.frais_mission ADD CONSTRAINT "frais_mission_dayId_fkey" FOREIGN KEY ("dayId") REFERENCES erp_missions(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.gpao_nomenclature_lignes ADD CONSTRAINT "gpao_nomenclature_lignes_refNom_fkey" FOREIGN KEY ("refNom") REFERENCES gpao_nomenclatures("refArt") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.gpao_operations_gamme ADD CONSTRAINT "gpao_operations_gamme_gammeId_fkey" FOREIGN KEY ("gammeId") REFERENCES gpao_gammes(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.gpao_operations_gamme ADD CONSTRAINT "gpao_operations_gamme_operationId_fkey" FOREIGN KEY ("operationId") REFERENCES gpao_operations(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.gpao_operations_gamme ADD CONSTRAINT "gpao_operations_gamme_posteChargeId_fkey" FOREIGN KEY ("posteChargeId") REFERENCES gpao_postes_charge(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.gpao_plannification ADD CONSTRAINT "gpao_plannification_posteChargeId_fkey" FOREIGN KEY ("posteChargeId") REFERENCES gpao_postes_charge(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.gps_positions ADD CONSTRAINT "gps_positions_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES commercials(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.gps_positions ADD CONSTRAINT "gps_positions_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES vehicles(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.grh_bulletin ADD CONSTRAINT "grh_bulletin_codeEmploye_fkey" FOREIGN KEY ("codeEmploye") REFERENCES grh_personnel("codeEmploye") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.grh_bulletin ADD CONSTRAINT "grh_bulletin_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES grh_session(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.grh_conge ADD CONSTRAINT "grh_conge_codeEmploye_fkey" FOREIGN KEY ("codeEmploye") REFERENCES grh_personnel("codeEmploye") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.grh_conge ADD CONSTRAINT "grh_conge_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES grh_session(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.grh_contrats ADD CONSTRAINT "grh_contrats_personnelId_fkey" FOREIGN KEY ("personnelId") REFERENCES grh_personnel(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.grh_personnel ADD CONSTRAINT "grh_personnel_categorieId_fkey" FOREIGN KEY ("categorieId") REFERENCES grh_categorie(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.grh_personnel ADD CONSTRAINT "grh_personnel_echelonId_fkey" FOREIGN KEY ("echelonId") REFERENCES grh_echelon(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.grh_personnel ADD CONSTRAINT "grh_personnel_fonctionId_fkey" FOREIGN KEY ("fonctionId") REFERENCES grh_fonction(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.grh_personnel ADD CONSTRAINT "grh_personnel_gradeId_fkey" FOREIGN KEY ("gradeId") REFERENCES grh_grade(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.grh_personnel ADD CONSTRAINT "grh_personnel_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES grh_service(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.grh_pointage ADD CONSTRAINT "grh_pointage_codeEmploye_fkey" FOREIGN KEY ("codeEmploye") REFERENCES grh_personnel("codeEmploye") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.grh_pointage ADD CONSTRAINT "grh_pointage_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES grh_session(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.inventaire_lignes ADD CONSTRAINT "inventaire_lignes_inventaireId_fkey" FOREIGN KEY ("inventaireId") REFERENCES inventaires(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.ligne_mission ADD CONSTRAINT "ligne_mission_dayId_fkey" FOREIGN KEY ("dayId") REFERENCES erp_missions(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.managers ADD CONSTRAINT "managers_userId_fkey" FOREIGN KEY ("userId") REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.order_lines ADD CONSTRAINT "order_lines_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES orders(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.order_lines ADD CONSTRAINT "order_lines_productId_fkey" FOREIGN KEY ("productId") REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.orders ADD CONSTRAINT "orders_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES clients(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.panier_lignes ADD CONSTRAINT "panier_lignes_panierId_fkey" FOREIGN KEY ("panierId") REFERENCES paniers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT "products_depotId_fkey" FOREIGN KEY ("depotId") REFERENCES depots(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.products ADD CONSTRAINT "products_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES suppliers(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.projet_jalons ADD CONSTRAINT "projet_jalons_projetId_fkey" FOREIGN KEY ("projetId") REFERENCES projets(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.purchase_documents ADD CONSTRAINT "purchase_documents_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES suppliers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.reclamation_client ADD CONSTRAINT "reclamation_client_dayId_fkey" FOREIGN KEY ("dayId") REFERENCES erp_missions(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.recordings ADD CONSTRAINT "recordings_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES commercials(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.recordings ADD CONSTRAINT "recordings_visitId_fkey" FOREIGN KEY ("visitId") REFERENCES visits(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.reglements ADD CONSTRAINT "reglements_bankAccountId_fkey" FOREIGN KEY ("bankAccountId") REFERENCES bank_accounts(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.reglements ADD CONSTRAINT "reglements_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES clients(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.reglements ADD CONSTRAINT "reglements_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES suppliers(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.rubrique_employe ADD CONSTRAINT "rubrique_employe_codeEmploye_fkey" FOREIGN KEY ("codeEmploye") REFERENCES grh_personnel("codeEmploye") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.rubrique_employe ADD CONSTRAINT "rubrique_employe_rubriqueId_fkey" FOREIGN KEY ("rubriqueId") REFERENCES rubrique_paie(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.rubrique_employe ADD CONSTRAINT "rubrique_employe_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES grh_session(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.stock_movements ADD CONSTRAINT "stock_movements_depotId_fkey" FOREIGN KEY ("depotId") REFERENCES depots(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.stock_movements ADD CONSTRAINT "stock_movements_productId_fkey" FOREIGN KEY ("productId") REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.stock_movements_ext ADD CONSTRAINT "stock_movements_ext_refDoc_fkey" FOREIGN KEY ("refDoc") REFERENCES documents_ext("refDoc") ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.vehicules_operations ADD CONSTRAINT "vehicules_operations_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES vehicles(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.visits ADD CONSTRAINT "visits_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES clients(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.visits ADD CONSTRAINT "visits_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES commercials(id) ON UPDATE CASCADE ON DELETE RESTRICT;
