-- Conversion des identifiants text (cuid) en integer auto-incrémenté.
-- Généré depuis le catalogue PostgreSQL. Les clés métier partagées avec la
-- production (articles_ext.refArt, documents_ext.refDoc, unite_art.unite,
-- gpao_nomenclatures.refArt) restent en text : ce sont les références de l'ERP.


-- 1. Correspondance ancien cuid → nouvel entier, dans l'ordre chronologique.
CREATE TEMP TABLE map_accounts AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "accounts";
CREATE INDEX ON map_accounts(ancien);
CREATE TEMP TABLE map_account_entries AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "account_entries";
CREATE INDEX ON map_account_entries(ancien);
CREATE TEMP TABLE map_claims AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "claims";
CREATE INDEX ON map_claims(ancien);
CREATE TEMP TABLE map_clients AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "clients";
CREATE INDEX ON map_clients(ancien);
CREATE TEMP TABLE map_commercials AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "commercials";
CREATE INDEX ON map_commercials(ancien);
CREATE TEMP TABLE map_depots AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "depots";
CREATE INDEX ON map_depots(ancien);
CREATE TEMP TABLE map_document_lines AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "document_lines";
CREATE INDEX ON map_document_lines(ancien);
CREATE TEMP TABLE map_documents AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "documents";
CREATE INDEX ON map_documents(ancien);
CREATE TEMP TABLE map_gps_positions AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "timestamp" NULLS LAST, id))::int AS nouveau FROM "gps_positions";
CREATE INDEX ON map_gps_positions(ancien);
CREATE TEMP TABLE map_journal_entries AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "journal_entries";
CREATE INDEX ON map_journal_entries(ancien);
CREATE TEMP TABLE map_managers AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "managers";
CREATE INDEX ON map_managers(ancien);
CREATE TEMP TABLE map_notifications AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "notifications";
CREATE INDEX ON map_notifications(ancien);
CREATE TEMP TABLE map_order_lines AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "order_lines";
CREATE INDEX ON map_order_lines(ancien);
CREATE TEMP TABLE map_orders AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "orders";
CREATE INDEX ON map_orders(ancien);
CREATE TEMP TABLE map_products AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "products";
CREATE INDEX ON map_products(ancien);
CREATE TEMP TABLE map_purchase_documents AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "purchase_documents";
CREATE INDEX ON map_purchase_documents(ancien);
CREATE TEMP TABLE map_recordings AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "recordings";
CREATE INDEX ON map_recordings(ancien);
CREATE TEMP TABLE map_reglements AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "reglements";
CREATE INDEX ON map_reglements(ancien);
CREATE TEMP TABLE map_stock_movements AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "stock_movements";
CREATE INDEX ON map_stock_movements(ancien);
CREATE TEMP TABLE map_suppliers AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "suppliers";
CREATE INDEX ON map_suppliers(ancien);
CREATE TEMP TABLE map_users AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "users";
CREATE INDEX ON map_users(ancien);
CREATE TEMP TABLE map_vehicles AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "vehicles";
CREATE INDEX ON map_vehicles(ancien);
CREATE TEMP TABLE map_visits AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "visits";
CREATE INDEX ON map_visits(ancien);
CREATE TEMP TABLE map_bank_accounts AS
  SELECT id AS ancien, (row_number() OVER (ORDER BY "createdAt" NULLS LAST, id))::int AS nouveau FROM "bank_accounts";
CREATE INDEX ON map_bank_accounts(ancien);

-- 2. Retirer les clés étrangères le temps de la bascule.
ALTER TABLE "managers" DROP CONSTRAINT "managers_userId_fkey";
ALTER TABLE "commercials" DROP CONSTRAINT "commercials_userId_fkey";
ALTER TABLE "commercials" DROP CONSTRAINT "commercials_vehicleId_fkey";
ALTER TABLE "clients" DROP CONSTRAINT "clients_userId_fkey";
ALTER TABLE "clients" DROP CONSTRAINT "clients_commercialId_fkey";
ALTER TABLE "gps_positions" DROP CONSTRAINT "gps_positions_commercialId_fkey";
ALTER TABLE "gps_positions" DROP CONSTRAINT "gps_positions_vehicleId_fkey";
ALTER TABLE "documents" DROP CONSTRAINT "documents_clientId_fkey";
ALTER TABLE "documents" DROP CONSTRAINT "documents_commercialId_fkey";
ALTER TABLE "document_lines" DROP CONSTRAINT "document_lines_documentId_fkey";
ALTER TABLE "document_lines" DROP CONSTRAINT "document_lines_productId_fkey";
ALTER TABLE "orders" DROP CONSTRAINT "orders_clientId_fkey";
ALTER TABLE "order_lines" DROP CONSTRAINT "order_lines_orderId_fkey";
ALTER TABLE "order_lines" DROP CONSTRAINT "order_lines_productId_fkey";
ALTER TABLE "visits" DROP CONSTRAINT "visits_commercialId_fkey";
ALTER TABLE "visits" DROP CONSTRAINT "visits_clientId_fkey";
ALTER TABLE "recordings" DROP CONSTRAINT "recordings_visitId_fkey";
ALTER TABLE "recordings" DROP CONSTRAINT "recordings_commercialId_fkey";
ALTER TABLE "claims" DROP CONSTRAINT "claims_clientId_fkey";
ALTER TABLE "products" DROP CONSTRAINT "products_depotId_fkey";
ALTER TABLE "products" DROP CONSTRAINT "products_supplierId_fkey";
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_productId_fkey";
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_depotId_fkey";
ALTER TABLE "purchase_documents" DROP CONSTRAINT "purchase_documents_supplierId_fkey";
ALTER TABLE "account_entries" DROP CONSTRAINT "account_entries_journalEntryId_fkey";
ALTER TABLE "account_entries" DROP CONSTRAINT "account_entries_accountId_fkey";
ALTER TABLE "reglements" DROP CONSTRAINT "reglements_clientId_fkey";
ALTER TABLE "reglements" DROP CONSTRAINT "reglements_supplierId_fkey";
ALTER TABLE "reglements" DROP CONSTRAINT "reglements_bankAccountId_fkey";
ALTER TABLE "vehicules_operations" DROP CONSTRAINT "vehicules_operations_vehicleId_fkey";

-- 3. Convertir chaque colonne référente en entier.
ALTER TABLE "managers" ADD COLUMN "userId__n" integer;
UPDATE "managers" s SET "userId__n" = m.nouveau FROM map_users m WHERE m.ancien = s."userId";
ALTER TABLE "managers" DROP COLUMN "userId";
ALTER TABLE "managers" RENAME COLUMN "userId__n" TO "userId";
ALTER TABLE "managers" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "commercials" ADD COLUMN "userId__n" integer;
UPDATE "commercials" s SET "userId__n" = m.nouveau FROM map_users m WHERE m.ancien = s."userId";
ALTER TABLE "commercials" DROP COLUMN "userId";
ALTER TABLE "commercials" RENAME COLUMN "userId__n" TO "userId";
ALTER TABLE "commercials" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "commercials" ADD COLUMN "vehicleId__n" integer;
UPDATE "commercials" s SET "vehicleId__n" = m.nouveau FROM map_vehicles m WHERE m.ancien = s."vehicleId";
ALTER TABLE "commercials" DROP COLUMN "vehicleId";
ALTER TABLE "commercials" RENAME COLUMN "vehicleId__n" TO "vehicleId";
ALTER TABLE "clients" ADD COLUMN "userId__n" integer;
UPDATE "clients" s SET "userId__n" = m.nouveau FROM map_users m WHERE m.ancien = s."userId";
ALTER TABLE "clients" DROP COLUMN "userId";
ALTER TABLE "clients" RENAME COLUMN "userId__n" TO "userId";
ALTER TABLE "clients" ADD COLUMN "commercialId__n" integer;
UPDATE "clients" s SET "commercialId__n" = m.nouveau FROM map_commercials m WHERE m.ancien = s."commercialId";
ALTER TABLE "clients" DROP COLUMN "commercialId";
ALTER TABLE "clients" RENAME COLUMN "commercialId__n" TO "commercialId";
ALTER TABLE "gps_positions" ADD COLUMN "commercialId__n" integer;
UPDATE "gps_positions" s SET "commercialId__n" = m.nouveau FROM map_commercials m WHERE m.ancien = s."commercialId";
ALTER TABLE "gps_positions" DROP COLUMN "commercialId";
ALTER TABLE "gps_positions" RENAME COLUMN "commercialId__n" TO "commercialId";
ALTER TABLE "gps_positions" ADD COLUMN "vehicleId__n" integer;
UPDATE "gps_positions" s SET "vehicleId__n" = m.nouveau FROM map_vehicles m WHERE m.ancien = s."vehicleId";
ALTER TABLE "gps_positions" DROP COLUMN "vehicleId";
ALTER TABLE "gps_positions" RENAME COLUMN "vehicleId__n" TO "vehicleId";
ALTER TABLE "documents" ADD COLUMN "clientId__n" integer;
UPDATE "documents" s SET "clientId__n" = m.nouveau FROM map_clients m WHERE m.ancien = s."clientId";
ALTER TABLE "documents" DROP COLUMN "clientId";
ALTER TABLE "documents" RENAME COLUMN "clientId__n" TO "clientId";
ALTER TABLE "documents" ALTER COLUMN "clientId" SET NOT NULL;
ALTER TABLE "documents" ADD COLUMN "commercialId__n" integer;
UPDATE "documents" s SET "commercialId__n" = m.nouveau FROM map_commercials m WHERE m.ancien = s."commercialId";
ALTER TABLE "documents" DROP COLUMN "commercialId";
ALTER TABLE "documents" RENAME COLUMN "commercialId__n" TO "commercialId";
ALTER TABLE "document_lines" ADD COLUMN "documentId__n" integer;
UPDATE "document_lines" s SET "documentId__n" = m.nouveau FROM map_documents m WHERE m.ancien = s."documentId";
ALTER TABLE "document_lines" DROP COLUMN "documentId";
ALTER TABLE "document_lines" RENAME COLUMN "documentId__n" TO "documentId";
ALTER TABLE "document_lines" ALTER COLUMN "documentId" SET NOT NULL;
ALTER TABLE "document_lines" ADD COLUMN "productId__n" integer;
UPDATE "document_lines" s SET "productId__n" = m.nouveau FROM map_products m WHERE m.ancien = s."productId";
ALTER TABLE "document_lines" DROP COLUMN "productId";
ALTER TABLE "document_lines" RENAME COLUMN "productId__n" TO "productId";
ALTER TABLE "document_lines" ALTER COLUMN "productId" SET NOT NULL;
ALTER TABLE "orders" ADD COLUMN "clientId__n" integer;
UPDATE "orders" s SET "clientId__n" = m.nouveau FROM map_clients m WHERE m.ancien = s."clientId";
ALTER TABLE "orders" DROP COLUMN "clientId";
ALTER TABLE "orders" RENAME COLUMN "clientId__n" TO "clientId";
ALTER TABLE "orders" ALTER COLUMN "clientId" SET NOT NULL;
ALTER TABLE "order_lines" ADD COLUMN "orderId__n" integer;
UPDATE "order_lines" s SET "orderId__n" = m.nouveau FROM map_orders m WHERE m.ancien = s."orderId";
ALTER TABLE "order_lines" DROP COLUMN "orderId";
ALTER TABLE "order_lines" RENAME COLUMN "orderId__n" TO "orderId";
ALTER TABLE "order_lines" ALTER COLUMN "orderId" SET NOT NULL;
ALTER TABLE "order_lines" ADD COLUMN "productId__n" integer;
UPDATE "order_lines" s SET "productId__n" = m.nouveau FROM map_products m WHERE m.ancien = s."productId";
ALTER TABLE "order_lines" DROP COLUMN "productId";
ALTER TABLE "order_lines" RENAME COLUMN "productId__n" TO "productId";
ALTER TABLE "order_lines" ALTER COLUMN "productId" SET NOT NULL;
ALTER TABLE "visits" ADD COLUMN "commercialId__n" integer;
UPDATE "visits" s SET "commercialId__n" = m.nouveau FROM map_commercials m WHERE m.ancien = s."commercialId";
ALTER TABLE "visits" DROP COLUMN "commercialId";
ALTER TABLE "visits" RENAME COLUMN "commercialId__n" TO "commercialId";
ALTER TABLE "visits" ALTER COLUMN "commercialId" SET NOT NULL;
ALTER TABLE "visits" ADD COLUMN "clientId__n" integer;
UPDATE "visits" s SET "clientId__n" = m.nouveau FROM map_clients m WHERE m.ancien = s."clientId";
ALTER TABLE "visits" DROP COLUMN "clientId";
ALTER TABLE "visits" RENAME COLUMN "clientId__n" TO "clientId";
ALTER TABLE "visits" ALTER COLUMN "clientId" SET NOT NULL;
ALTER TABLE "recordings" ADD COLUMN "visitId__n" integer;
UPDATE "recordings" s SET "visitId__n" = m.nouveau FROM map_visits m WHERE m.ancien = s."visitId";
ALTER TABLE "recordings" DROP COLUMN "visitId";
ALTER TABLE "recordings" RENAME COLUMN "visitId__n" TO "visitId";
ALTER TABLE "recordings" ALTER COLUMN "visitId" SET NOT NULL;
ALTER TABLE "recordings" ADD COLUMN "commercialId__n" integer;
UPDATE "recordings" s SET "commercialId__n" = m.nouveau FROM map_commercials m WHERE m.ancien = s."commercialId";
ALTER TABLE "recordings" DROP COLUMN "commercialId";
ALTER TABLE "recordings" RENAME COLUMN "commercialId__n" TO "commercialId";
ALTER TABLE "recordings" ALTER COLUMN "commercialId" SET NOT NULL;
ALTER TABLE "claims" ADD COLUMN "clientId__n" integer;
UPDATE "claims" s SET "clientId__n" = m.nouveau FROM map_clients m WHERE m.ancien = s."clientId";
ALTER TABLE "claims" DROP COLUMN "clientId";
ALTER TABLE "claims" RENAME COLUMN "clientId__n" TO "clientId";
ALTER TABLE "claims" ALTER COLUMN "clientId" SET NOT NULL;
ALTER TABLE "products" ADD COLUMN "depotId__n" integer;
UPDATE "products" s SET "depotId__n" = m.nouveau FROM map_depots m WHERE m.ancien = s."depotId";
ALTER TABLE "products" DROP COLUMN "depotId";
ALTER TABLE "products" RENAME COLUMN "depotId__n" TO "depotId";
ALTER TABLE "products" ADD COLUMN "supplierId__n" integer;
UPDATE "products" s SET "supplierId__n" = m.nouveau FROM map_suppliers m WHERE m.ancien = s."supplierId";
ALTER TABLE "products" DROP COLUMN "supplierId";
ALTER TABLE "products" RENAME COLUMN "supplierId__n" TO "supplierId";
ALTER TABLE "stock_movements" ADD COLUMN "productId__n" integer;
UPDATE "stock_movements" s SET "productId__n" = m.nouveau FROM map_products m WHERE m.ancien = s."productId";
ALTER TABLE "stock_movements" DROP COLUMN "productId";
ALTER TABLE "stock_movements" RENAME COLUMN "productId__n" TO "productId";
ALTER TABLE "stock_movements" ALTER COLUMN "productId" SET NOT NULL;
ALTER TABLE "stock_movements" ADD COLUMN "depotId__n" integer;
UPDATE "stock_movements" s SET "depotId__n" = m.nouveau FROM map_depots m WHERE m.ancien = s."depotId";
ALTER TABLE "stock_movements" DROP COLUMN "depotId";
ALTER TABLE "stock_movements" RENAME COLUMN "depotId__n" TO "depotId";
ALTER TABLE "purchase_documents" ADD COLUMN "supplierId__n" integer;
UPDATE "purchase_documents" s SET "supplierId__n" = m.nouveau FROM map_suppliers m WHERE m.ancien = s."supplierId";
ALTER TABLE "purchase_documents" DROP COLUMN "supplierId";
ALTER TABLE "purchase_documents" RENAME COLUMN "supplierId__n" TO "supplierId";
ALTER TABLE "purchase_documents" ALTER COLUMN "supplierId" SET NOT NULL;
ALTER TABLE "account_entries" ADD COLUMN "journalEntryId__n" integer;
UPDATE "account_entries" s SET "journalEntryId__n" = m.nouveau FROM map_journal_entries m WHERE m.ancien = s."journalEntryId";
ALTER TABLE "account_entries" DROP COLUMN "journalEntryId";
ALTER TABLE "account_entries" RENAME COLUMN "journalEntryId__n" TO "journalEntryId";
ALTER TABLE "account_entries" ALTER COLUMN "journalEntryId" SET NOT NULL;
ALTER TABLE "account_entries" ADD COLUMN "accountId__n" integer;
UPDATE "account_entries" s SET "accountId__n" = m.nouveau FROM map_accounts m WHERE m.ancien = s."accountId";
ALTER TABLE "account_entries" DROP COLUMN "accountId";
ALTER TABLE "account_entries" RENAME COLUMN "accountId__n" TO "accountId";
ALTER TABLE "account_entries" ALTER COLUMN "accountId" SET NOT NULL;
ALTER TABLE "reglements" ADD COLUMN "clientId__n" integer;
UPDATE "reglements" s SET "clientId__n" = m.nouveau FROM map_clients m WHERE m.ancien = s."clientId";
ALTER TABLE "reglements" DROP COLUMN "clientId";
ALTER TABLE "reglements" RENAME COLUMN "clientId__n" TO "clientId";
ALTER TABLE "reglements" ADD COLUMN "supplierId__n" integer;
UPDATE "reglements" s SET "supplierId__n" = m.nouveau FROM map_suppliers m WHERE m.ancien = s."supplierId";
ALTER TABLE "reglements" DROP COLUMN "supplierId";
ALTER TABLE "reglements" RENAME COLUMN "supplierId__n" TO "supplierId";
ALTER TABLE "reglements" ADD COLUMN "bankAccountId__n" integer;
UPDATE "reglements" s SET "bankAccountId__n" = m.nouveau FROM map_bank_accounts m WHERE m.ancien = s."bankAccountId";
ALTER TABLE "reglements" DROP COLUMN "bankAccountId";
ALTER TABLE "reglements" RENAME COLUMN "bankAccountId__n" TO "bankAccountId";
ALTER TABLE "vehicules_operations" ADD COLUMN "vehicleId__n" integer;
UPDATE "vehicules_operations" s SET "vehicleId__n" = m.nouveau FROM map_vehicles m WHERE m.ancien = s."vehicleId";
ALTER TABLE "vehicules_operations" DROP COLUMN "vehicleId";
ALTER TABLE "vehicules_operations" RENAME COLUMN "vehicleId__n" TO "vehicleId";
ALTER TABLE "vehicules_operations" ALTER COLUMN "vehicleId" SET NOT NULL;
ALTER TABLE "alertes_acquittees" ADD COLUMN "userId__n" integer;
UPDATE "alertes_acquittees" s SET "userId__n" = m.nouveau FROM map_users m WHERE m.ancien = s."userId";
ALTER TABLE "alertes_acquittees" DROP COLUMN "userId";
ALTER TABLE "alertes_acquittees" RENAME COLUMN "userId__n" TO "userId";
ALTER TABLE "alertes_acquittees" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "notifications" ADD COLUMN "userId__n" integer;
UPDATE "notifications" s SET "userId__n" = m.nouveau FROM map_users m WHERE m.ancien = s."userId";
ALTER TABLE "notifications" DROP COLUMN "userId";
ALTER TABLE "notifications" RENAME COLUMN "userId__n" TO "userId";
ALTER TABLE "notifications" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "accounts" ADD COLUMN "parentId__n" integer;
UPDATE "accounts" s SET "parentId__n" = m.nouveau FROM map_accounts m WHERE m.ancien = s."parentId";
ALTER TABLE "accounts" DROP COLUMN "parentId";
ALTER TABLE "accounts" RENAME COLUMN "parentId__n" TO "parentId";

-- 4. Convertir chaque clé primaire, puis l'armer en auto-incrément.
ALTER TABLE "accounts" ADD COLUMN "id__n" integer;
UPDATE "accounts" t SET "id__n" = m.nouveau FROM map_accounts m WHERE m.ancien = t.id;
ALTER TABLE "accounts" DROP CONSTRAINT "accounts_pkey";
ALTER TABLE "accounts" DROP COLUMN id;
ALTER TABLE "accounts" RENAME COLUMN "id__n" TO id;
ALTER TABLE "accounts" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "accounts_id_seq" OWNED BY "accounts".id;
ALTER TABLE "accounts" ALTER COLUMN id SET DEFAULT nextval('"accounts_id_seq"');
SELECT setval('"accounts_id_seq"', COALESCE((SELECT max(id) FROM "accounts"), 0) + 1, true);
ALTER TABLE "account_entries" ADD COLUMN "id__n" integer;
UPDATE "account_entries" t SET "id__n" = m.nouveau FROM map_account_entries m WHERE m.ancien = t.id;
ALTER TABLE "account_entries" DROP CONSTRAINT "account_entries_pkey";
ALTER TABLE "account_entries" DROP COLUMN id;
ALTER TABLE "account_entries" RENAME COLUMN "id__n" TO id;
ALTER TABLE "account_entries" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "account_entries" ADD CONSTRAINT "account_entries_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "account_entries_id_seq" OWNED BY "account_entries".id;
ALTER TABLE "account_entries" ALTER COLUMN id SET DEFAULT nextval('"account_entries_id_seq"');
SELECT setval('"account_entries_id_seq"', COALESCE((SELECT max(id) FROM "account_entries"), 0) + 1, true);
ALTER TABLE "claims" ADD COLUMN "id__n" integer;
UPDATE "claims" t SET "id__n" = m.nouveau FROM map_claims m WHERE m.ancien = t.id;
ALTER TABLE "claims" DROP CONSTRAINT "claims_pkey";
ALTER TABLE "claims" DROP COLUMN id;
ALTER TABLE "claims" RENAME COLUMN "id__n" TO id;
ALTER TABLE "claims" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "claims" ADD CONSTRAINT "claims_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "claims_id_seq" OWNED BY "claims".id;
ALTER TABLE "claims" ALTER COLUMN id SET DEFAULT nextval('"claims_id_seq"');
SELECT setval('"claims_id_seq"', COALESCE((SELECT max(id) FROM "claims"), 0) + 1, true);
ALTER TABLE "clients" ADD COLUMN "id__n" integer;
UPDATE "clients" t SET "id__n" = m.nouveau FROM map_clients m WHERE m.ancien = t.id;
ALTER TABLE "clients" DROP CONSTRAINT "clients_pkey";
ALTER TABLE "clients" DROP COLUMN id;
ALTER TABLE "clients" RENAME COLUMN "id__n" TO id;
ALTER TABLE "clients" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "clients" ADD CONSTRAINT "clients_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "clients_id_seq" OWNED BY "clients".id;
ALTER TABLE "clients" ALTER COLUMN id SET DEFAULT nextval('"clients_id_seq"');
SELECT setval('"clients_id_seq"', COALESCE((SELECT max(id) FROM "clients"), 0) + 1, true);
ALTER TABLE "commercials" ADD COLUMN "id__n" integer;
UPDATE "commercials" t SET "id__n" = m.nouveau FROM map_commercials m WHERE m.ancien = t.id;
ALTER TABLE "commercials" DROP CONSTRAINT "commercials_pkey";
ALTER TABLE "commercials" DROP COLUMN id;
ALTER TABLE "commercials" RENAME COLUMN "id__n" TO id;
ALTER TABLE "commercials" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "commercials" ADD CONSTRAINT "commercials_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "commercials_id_seq" OWNED BY "commercials".id;
ALTER TABLE "commercials" ALTER COLUMN id SET DEFAULT nextval('"commercials_id_seq"');
SELECT setval('"commercials_id_seq"', COALESCE((SELECT max(id) FROM "commercials"), 0) + 1, true);
ALTER TABLE "depots" ADD COLUMN "id__n" integer;
UPDATE "depots" t SET "id__n" = m.nouveau FROM map_depots m WHERE m.ancien = t.id;
ALTER TABLE "depots" DROP CONSTRAINT "depots_pkey";
ALTER TABLE "depots" DROP COLUMN id;
ALTER TABLE "depots" RENAME COLUMN "id__n" TO id;
ALTER TABLE "depots" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "depots" ADD CONSTRAINT "depots_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "depots_id_seq" OWNED BY "depots".id;
ALTER TABLE "depots" ALTER COLUMN id SET DEFAULT nextval('"depots_id_seq"');
SELECT setval('"depots_id_seq"', COALESCE((SELECT max(id) FROM "depots"), 0) + 1, true);
ALTER TABLE "document_lines" ADD COLUMN "id__n" integer;
UPDATE "document_lines" t SET "id__n" = m.nouveau FROM map_document_lines m WHERE m.ancien = t.id;
ALTER TABLE "document_lines" DROP CONSTRAINT "document_lines_pkey";
ALTER TABLE "document_lines" DROP COLUMN id;
ALTER TABLE "document_lines" RENAME COLUMN "id__n" TO id;
ALTER TABLE "document_lines" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "document_lines" ADD CONSTRAINT "document_lines_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "document_lines_id_seq" OWNED BY "document_lines".id;
ALTER TABLE "document_lines" ALTER COLUMN id SET DEFAULT nextval('"document_lines_id_seq"');
SELECT setval('"document_lines_id_seq"', COALESCE((SELECT max(id) FROM "document_lines"), 0) + 1, true);
ALTER TABLE "documents" ADD COLUMN "id__n" integer;
UPDATE "documents" t SET "id__n" = m.nouveau FROM map_documents m WHERE m.ancien = t.id;
ALTER TABLE "documents" DROP CONSTRAINT "documents_pkey";
ALTER TABLE "documents" DROP COLUMN id;
ALTER TABLE "documents" RENAME COLUMN "id__n" TO id;
ALTER TABLE "documents" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "documents" ADD CONSTRAINT "documents_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "documents_id_seq" OWNED BY "documents".id;
ALTER TABLE "documents" ALTER COLUMN id SET DEFAULT nextval('"documents_id_seq"');
SELECT setval('"documents_id_seq"', COALESCE((SELECT max(id) FROM "documents"), 0) + 1, true);
ALTER TABLE "gps_positions" ADD COLUMN "id__n" integer;
UPDATE "gps_positions" t SET "id__n" = m.nouveau FROM map_gps_positions m WHERE m.ancien = t.id;
ALTER TABLE "gps_positions" DROP CONSTRAINT "gps_positions_pkey";
ALTER TABLE "gps_positions" DROP COLUMN id;
ALTER TABLE "gps_positions" RENAME COLUMN "id__n" TO id;
ALTER TABLE "gps_positions" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "gps_positions" ADD CONSTRAINT "gps_positions_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "gps_positions_id_seq" OWNED BY "gps_positions".id;
ALTER TABLE "gps_positions" ALTER COLUMN id SET DEFAULT nextval('"gps_positions_id_seq"');
SELECT setval('"gps_positions_id_seq"', COALESCE((SELECT max(id) FROM "gps_positions"), 0) + 1, true);
ALTER TABLE "journal_entries" ADD COLUMN "id__n" integer;
UPDATE "journal_entries" t SET "id__n" = m.nouveau FROM map_journal_entries m WHERE m.ancien = t.id;
ALTER TABLE "journal_entries" DROP CONSTRAINT "journal_entries_pkey";
ALTER TABLE "journal_entries" DROP COLUMN id;
ALTER TABLE "journal_entries" RENAME COLUMN "id__n" TO id;
ALTER TABLE "journal_entries" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "journal_entries_id_seq" OWNED BY "journal_entries".id;
ALTER TABLE "journal_entries" ALTER COLUMN id SET DEFAULT nextval('"journal_entries_id_seq"');
SELECT setval('"journal_entries_id_seq"', COALESCE((SELECT max(id) FROM "journal_entries"), 0) + 1, true);
ALTER TABLE "managers" ADD COLUMN "id__n" integer;
UPDATE "managers" t SET "id__n" = m.nouveau FROM map_managers m WHERE m.ancien = t.id;
ALTER TABLE "managers" DROP CONSTRAINT "managers_pkey";
ALTER TABLE "managers" DROP COLUMN id;
ALTER TABLE "managers" RENAME COLUMN "id__n" TO id;
ALTER TABLE "managers" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "managers" ADD CONSTRAINT "managers_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "managers_id_seq" OWNED BY "managers".id;
ALTER TABLE "managers" ALTER COLUMN id SET DEFAULT nextval('"managers_id_seq"');
SELECT setval('"managers_id_seq"', COALESCE((SELECT max(id) FROM "managers"), 0) + 1, true);
ALTER TABLE "notifications" ADD COLUMN "id__n" integer;
UPDATE "notifications" t SET "id__n" = m.nouveau FROM map_notifications m WHERE m.ancien = t.id;
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_pkey";
ALTER TABLE "notifications" DROP COLUMN id;
ALTER TABLE "notifications" RENAME COLUMN "id__n" TO id;
ALTER TABLE "notifications" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "notifications_id_seq" OWNED BY "notifications".id;
ALTER TABLE "notifications" ALTER COLUMN id SET DEFAULT nextval('"notifications_id_seq"');
SELECT setval('"notifications_id_seq"', COALESCE((SELECT max(id) FROM "notifications"), 0) + 1, true);
ALTER TABLE "order_lines" ADD COLUMN "id__n" integer;
UPDATE "order_lines" t SET "id__n" = m.nouveau FROM map_order_lines m WHERE m.ancien = t.id;
ALTER TABLE "order_lines" DROP CONSTRAINT "order_lines_pkey";
ALTER TABLE "order_lines" DROP COLUMN id;
ALTER TABLE "order_lines" RENAME COLUMN "id__n" TO id;
ALTER TABLE "order_lines" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "order_lines" ADD CONSTRAINT "order_lines_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "order_lines_id_seq" OWNED BY "order_lines".id;
ALTER TABLE "order_lines" ALTER COLUMN id SET DEFAULT nextval('"order_lines_id_seq"');
SELECT setval('"order_lines_id_seq"', COALESCE((SELECT max(id) FROM "order_lines"), 0) + 1, true);
ALTER TABLE "orders" ADD COLUMN "id__n" integer;
UPDATE "orders" t SET "id__n" = m.nouveau FROM map_orders m WHERE m.ancien = t.id;
ALTER TABLE "orders" DROP CONSTRAINT "orders_pkey";
ALTER TABLE "orders" DROP COLUMN id;
ALTER TABLE "orders" RENAME COLUMN "id__n" TO id;
ALTER TABLE "orders" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "orders" ADD CONSTRAINT "orders_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "orders_id_seq" OWNED BY "orders".id;
ALTER TABLE "orders" ALTER COLUMN id SET DEFAULT nextval('"orders_id_seq"');
SELECT setval('"orders_id_seq"', COALESCE((SELECT max(id) FROM "orders"), 0) + 1, true);
ALTER TABLE "products" ADD COLUMN "id__n" integer;
UPDATE "products" t SET "id__n" = m.nouveau FROM map_products m WHERE m.ancien = t.id;
ALTER TABLE "products" DROP CONSTRAINT "products_pkey";
ALTER TABLE "products" DROP COLUMN id;
ALTER TABLE "products" RENAME COLUMN "id__n" TO id;
ALTER TABLE "products" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "products" ADD CONSTRAINT "products_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "products_id_seq" OWNED BY "products".id;
ALTER TABLE "products" ALTER COLUMN id SET DEFAULT nextval('"products_id_seq"');
SELECT setval('"products_id_seq"', COALESCE((SELECT max(id) FROM "products"), 0) + 1, true);
ALTER TABLE "purchase_documents" ADD COLUMN "id__n" integer;
UPDATE "purchase_documents" t SET "id__n" = m.nouveau FROM map_purchase_documents m WHERE m.ancien = t.id;
ALTER TABLE "purchase_documents" DROP CONSTRAINT "purchase_documents_pkey";
ALTER TABLE "purchase_documents" DROP COLUMN id;
ALTER TABLE "purchase_documents" RENAME COLUMN "id__n" TO id;
ALTER TABLE "purchase_documents" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "purchase_documents" ADD CONSTRAINT "purchase_documents_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "purchase_documents_id_seq" OWNED BY "purchase_documents".id;
ALTER TABLE "purchase_documents" ALTER COLUMN id SET DEFAULT nextval('"purchase_documents_id_seq"');
SELECT setval('"purchase_documents_id_seq"', COALESCE((SELECT max(id) FROM "purchase_documents"), 0) + 1, true);
ALTER TABLE "recordings" ADD COLUMN "id__n" integer;
UPDATE "recordings" t SET "id__n" = m.nouveau FROM map_recordings m WHERE m.ancien = t.id;
ALTER TABLE "recordings" DROP CONSTRAINT "recordings_pkey";
ALTER TABLE "recordings" DROP COLUMN id;
ALTER TABLE "recordings" RENAME COLUMN "id__n" TO id;
ALTER TABLE "recordings" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "recordings" ADD CONSTRAINT "recordings_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "recordings_id_seq" OWNED BY "recordings".id;
ALTER TABLE "recordings" ALTER COLUMN id SET DEFAULT nextval('"recordings_id_seq"');
SELECT setval('"recordings_id_seq"', COALESCE((SELECT max(id) FROM "recordings"), 0) + 1, true);
ALTER TABLE "reglements" ADD COLUMN "id__n" integer;
UPDATE "reglements" t SET "id__n" = m.nouveau FROM map_reglements m WHERE m.ancien = t.id;
ALTER TABLE "reglements" DROP CONSTRAINT "reglements_pkey";
ALTER TABLE "reglements" DROP COLUMN id;
ALTER TABLE "reglements" RENAME COLUMN "id__n" TO id;
ALTER TABLE "reglements" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "reglements" ADD CONSTRAINT "reglements_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "reglements_id_seq" OWNED BY "reglements".id;
ALTER TABLE "reglements" ALTER COLUMN id SET DEFAULT nextval('"reglements_id_seq"');
SELECT setval('"reglements_id_seq"', COALESCE((SELECT max(id) FROM "reglements"), 0) + 1, true);
ALTER TABLE "stock_movements" ADD COLUMN "id__n" integer;
UPDATE "stock_movements" t SET "id__n" = m.nouveau FROM map_stock_movements m WHERE m.ancien = t.id;
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_pkey";
ALTER TABLE "stock_movements" DROP COLUMN id;
ALTER TABLE "stock_movements" RENAME COLUMN "id__n" TO id;
ALTER TABLE "stock_movements" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "stock_movements_id_seq" OWNED BY "stock_movements".id;
ALTER TABLE "stock_movements" ALTER COLUMN id SET DEFAULT nextval('"stock_movements_id_seq"');
SELECT setval('"stock_movements_id_seq"', COALESCE((SELECT max(id) FROM "stock_movements"), 0) + 1, true);
ALTER TABLE "suppliers" ADD COLUMN "id__n" integer;
UPDATE "suppliers" t SET "id__n" = m.nouveau FROM map_suppliers m WHERE m.ancien = t.id;
ALTER TABLE "suppliers" DROP CONSTRAINT "suppliers_pkey";
ALTER TABLE "suppliers" DROP COLUMN id;
ALTER TABLE "suppliers" RENAME COLUMN "id__n" TO id;
ALTER TABLE "suppliers" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "suppliers" ADD CONSTRAINT "suppliers_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "suppliers_id_seq" OWNED BY "suppliers".id;
ALTER TABLE "suppliers" ALTER COLUMN id SET DEFAULT nextval('"suppliers_id_seq"');
SELECT setval('"suppliers_id_seq"', COALESCE((SELECT max(id) FROM "suppliers"), 0) + 1, true);
ALTER TABLE "users" ADD COLUMN "id__n" integer;
UPDATE "users" t SET "id__n" = m.nouveau FROM map_users m WHERE m.ancien = t.id;
ALTER TABLE "users" DROP CONSTRAINT "users_pkey";
ALTER TABLE "users" DROP COLUMN id;
ALTER TABLE "users" RENAME COLUMN "id__n" TO id;
ALTER TABLE "users" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "users_id_seq" OWNED BY "users".id;
ALTER TABLE "users" ALTER COLUMN id SET DEFAULT nextval('"users_id_seq"');
SELECT setval('"users_id_seq"', COALESCE((SELECT max(id) FROM "users"), 0) + 1, true);
ALTER TABLE "vehicles" ADD COLUMN "id__n" integer;
UPDATE "vehicles" t SET "id__n" = m.nouveau FROM map_vehicles m WHERE m.ancien = t.id;
ALTER TABLE "vehicles" DROP CONSTRAINT "vehicles_pkey";
ALTER TABLE "vehicles" DROP COLUMN id;
ALTER TABLE "vehicles" RENAME COLUMN "id__n" TO id;
ALTER TABLE "vehicles" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "vehicles_id_seq" OWNED BY "vehicles".id;
ALTER TABLE "vehicles" ALTER COLUMN id SET DEFAULT nextval('"vehicles_id_seq"');
SELECT setval('"vehicles_id_seq"', COALESCE((SELECT max(id) FROM "vehicles"), 0) + 1, true);
ALTER TABLE "visits" ADD COLUMN "id__n" integer;
UPDATE "visits" t SET "id__n" = m.nouveau FROM map_visits m WHERE m.ancien = t.id;
ALTER TABLE "visits" DROP CONSTRAINT "visits_pkey";
ALTER TABLE "visits" DROP COLUMN id;
ALTER TABLE "visits" RENAME COLUMN "id__n" TO id;
ALTER TABLE "visits" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "visits" ADD CONSTRAINT "visits_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "visits_id_seq" OWNED BY "visits".id;
ALTER TABLE "visits" ALTER COLUMN id SET DEFAULT nextval('"visits_id_seq"');
SELECT setval('"visits_id_seq"', COALESCE((SELECT max(id) FROM "visits"), 0) + 1, true);
ALTER TABLE "bank_accounts" ADD COLUMN "id__n" integer;
UPDATE "bank_accounts" t SET "id__n" = m.nouveau FROM map_bank_accounts m WHERE m.ancien = t.id;
ALTER TABLE "bank_accounts" DROP CONSTRAINT "bank_accounts_pkey";
ALTER TABLE "bank_accounts" DROP COLUMN id;
ALTER TABLE "bank_accounts" RENAME COLUMN "id__n" TO id;
ALTER TABLE "bank_accounts" ALTER COLUMN id SET NOT NULL;
ALTER TABLE "bank_accounts" ADD CONSTRAINT "bank_accounts_pkey" PRIMARY KEY (id);
CREATE SEQUENCE "bank_accounts_id_seq" OWNED BY "bank_accounts".id;
ALTER TABLE "bank_accounts" ALTER COLUMN id SET DEFAULT nextval('"bank_accounts_id_seq"');
SELECT setval('"bank_accounts_id_seq"', COALESCE((SELECT max(id) FROM "bank_accounts"), 0) + 1, true);

-- 5. Rétablir les clés étrangères à l'identique.
ALTER TABLE "managers" ADD CONSTRAINT "managers_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "commercials" ADD CONSTRAINT "commercials_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "commercials" ADD CONSTRAINT "commercials_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "clients" ADD CONSTRAINT "clients_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "clients" ADD CONSTRAINT "clients_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES "commercials"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "gps_positions" ADD CONSTRAINT "gps_positions_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES "commercials"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "gps_positions" ADD CONSTRAINT "gps_positions_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "documents" ADD CONSTRAINT "documents_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "documents" ADD CONSTRAINT "documents_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES "commercials"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "document_lines" ADD CONSTRAINT "document_lines_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "documents"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "document_lines" ADD CONSTRAINT "document_lines_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "orders" ADD CONSTRAINT "orders_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "order_lines" ADD CONSTRAINT "order_lines_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "order_lines" ADD CONSTRAINT "order_lines_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "visits" ADD CONSTRAINT "visits_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES "commercials"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "visits" ADD CONSTRAINT "visits_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "recordings" ADD CONSTRAINT "recordings_visitId_fkey" FOREIGN KEY ("visitId") REFERENCES "visits"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "recordings" ADD CONSTRAINT "recordings_commercialId_fkey" FOREIGN KEY ("commercialId") REFERENCES "commercials"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "claims" ADD CONSTRAINT "claims_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "products" ADD CONSTRAINT "products_depotId_fkey" FOREIGN KEY ("depotId") REFERENCES "depots"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "products" ADD CONSTRAINT "products_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "suppliers"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_depotId_fkey" FOREIGN KEY ("depotId") REFERENCES "depots"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "purchase_documents" ADD CONSTRAINT "purchase_documents_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "suppliers"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "account_entries" ADD CONSTRAINT "account_entries_journalEntryId_fkey" FOREIGN KEY ("journalEntryId") REFERENCES "journal_entries"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "account_entries" ADD CONSTRAINT "account_entries_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "accounts"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "reglements" ADD CONSTRAINT "reglements_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "reglements" ADD CONSTRAINT "reglements_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "suppliers"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "reglements" ADD CONSTRAINT "reglements_bankAccountId_fkey" FOREIGN KEY ("bankAccountId") REFERENCES "bank_accounts"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "vehicules_operations" ADD CONSTRAINT "vehicules_operations_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- 6. Recréer les index et contraintes uniques emportés par la conversion.
DROP INDEX IF EXISTS "managers_userId_key";
CREATE UNIQUE INDEX "managers_userId_key" ON public.managers USING btree ("userId");
DROP INDEX IF EXISTS "commercials_userId_key";
CREATE UNIQUE INDEX "commercials_userId_key" ON public.commercials USING btree ("userId");
DROP INDEX IF EXISTS "commercials_vehicleId_key";
CREATE UNIQUE INDEX "commercials_vehicleId_key" ON public.commercials USING btree ("vehicleId");
DROP INDEX IF EXISTS "clients_userId_key";
CREATE UNIQUE INDEX "clients_userId_key" ON public.clients USING btree ("userId");
DROP INDEX IF EXISTS "vehicules_operations_vehicleId_idx";
CREATE INDEX "vehicules_operations_vehicleId_idx" ON public.vehicules_operations USING btree ("vehicleId");
DROP INDEX IF EXISTS "alertes_acquittees_userId_cle_key";
CREATE UNIQUE INDEX "alertes_acquittees_userId_cle_key" ON public.alertes_acquittees USING btree ("userId", cle);
DROP INDEX IF EXISTS "alertes_acquittees_userId_idx";
CREATE INDEX "alertes_acquittees_userId_idx" ON public.alertes_acquittees USING btree ("userId");

